FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    gfortran \
    && rm -rf /var/lib/apt/lists/*  

WORKDIR /preprocess
COPY preprocess .
COPY cases ./cases

RUN gfortran -O3 -funroll-loops -fopenmp \
    makeGrid/modules/*.f90 \
    makeGrid/main.f90 \
    -o makeGrid.exe
